package com.example.demo.Controllers.Levels;

import com.example.demo.Controllers.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.util.ArrayList;
import java.util.List;

public class Level1 {
    public static Pane gameRoot = new Pane();
    public static Pane appRoot = new Pane();
    public static Pane extraGameRoot = new Pane();
    public static ImageView imageViewHero = new ImageView(new Image("Images/Sprites/SpriteHero.png"));
    public static ImageView imageViewHeroViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteHeroViewFromAbove.png"));
    public static ImageView imageViewCoin = new ImageView(new Image("Images/Sprites/SpriteCoin.png"));
    public static ImageView imageViewCoinViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteCoinViewFromAbove.png"));
    public static List<Obstacle> listOfObstacles = new ArrayList<>();
    public static List<ObstacleViewFromAbove> listOfObstaclesViewFromAbove = new ArrayList<>();
    public static List<Integer> list = new ArrayList<>();
    public static List<Integer> listAbove = new ArrayList<>();
    public static Integer level = 1;
    public static ImageView backgroundSkyImage = new ImageView(new Image("Images/Level1/Sunset.png"));
    public static ImageView backgroundGroundImage = new ImageView(new Image("Images/Level1/GroundAboveForSunset.png"));
    public static void start(Stage stage) {
        Image wall = new Image("Images/Walls/Wall.jpg");
        Image highWall = new Image("Images/Walls/HighWall.jpg");
        Obstacle obstacle = new Obstacle(3000, 250, new Image("Images/Level1/GroundForSunset.png"));
        Obstacle obstacle3 = new Obstacle(70, 210, highWall);
        Obstacle obstacle4 = new Obstacle(70, 210, highWall);
        Obstacle obstacle5 = new Obstacle(70, 210, highWall);
        Obstacle obstacle6 = new Obstacle(70, 70, wall);
        Obstacle obstacle7 = new Obstacle(70, 70, wall);
        Obstacle obstacle8 = new Obstacle(70, 70, wall);
        Obstacle obstacle9 = new Obstacle(70, 70, wall);
        Obstacle obstacle10 = new Obstacle(70, 70, wall);
        Image longWall = new Image("Images/Walls/LongWall.jpg");
        ObstacleViewFromAbove obstacleViewFromAbove = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove2 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove3 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove4 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove5 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove6 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove7 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove8 = new ObstacleViewFromAbove(70, 900,longWall);
        ObstacleViewFromAbove obstacleViewFromAbove9 = new ObstacleViewFromAbove(70, 900,longWall);
        ObstacleViewFromAbove obstacleViewFromAbove10 = new ObstacleViewFromAbove(70, 900,longWall);
        ObstacleViewFromAbove obstacleViewFromAbove11 = new ObstacleViewFromAbove(70, 900,longWall);
        obstacle.setTranslateY(630);
        obstacle3.setTranslateX(1000);
        obstacle3.setTranslateY(420);
        obstacle4.setTranslateX(1700);
        obstacle4.setTranslateY(420);
        obstacle5.setTranslateX(2400);
        obstacle5.setTranslateY(420);
        obstacle6.setTranslateY(560);
        obstacle6.setTranslateX(2700);
        obstacle7.setTranslateY(560);
        obstacle7.setTranslateX(2000);
        obstacle8.setTranslateY(560);
        obstacle8.setTranslateX(1350);
        obstacle9.setTranslateY(560);
        obstacle9.setTranslateX(1420);
        obstacle10.setTranslateY(490);
        obstacle10.setTranslateX(1420);
        obstacleViewFromAbove.setTranslateX(2400);
        obstacleViewFromAbove.setTranslateY(725);
        obstacleViewFromAbove2.setTranslateX(1000);
        obstacleViewFromAbove3.setTranslateX(1700);
        obstacleViewFromAbove3.setTranslateY(795);
        obstacleViewFromAbove4.setTranslateX(2400);
        obstacleViewFromAbove4.setTranslateY(655);
        obstacleViewFromAbove5.setTranslateX(2400);
        obstacleViewFromAbove5.setTranslateY(795);
        obstacleViewFromAbove6.setTranslateX(2400);
        obstacleViewFromAbove6.setTranslateY(655);
        obstacleViewFromAbove7.setTranslateX(2400);
        obstacleViewFromAbove7.setTranslateY(585);
        obstacleViewFromAbove8.setTranslateX(2700);
        obstacleViewFromAbove9.setTranslateX(2000);
        obstacleViewFromAbove10.setTranslateX(1350);
        obstacleViewFromAbove11.setTranslateX(1420);
        listOfObstacles.add(obstacle);
        listOfObstacles.add(obstacle3);
        listOfObstacles.add(obstacle4);
        listOfObstacles.add(obstacle5);
        listOfObstacles.add(obstacle6);
        listOfObstacles.add(obstacle7);
        listOfObstacles.add(obstacle8);
        listOfObstacles.add(obstacle9);
        listOfObstacles.add(obstacle10);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove2);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove3);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove4);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove5);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove6);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove7);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove8);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove9);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove10);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove11);
        listOfObstacles.forEach(e -> list.add((int) e.getTranslateX()));
        listOfObstaclesViewFromAbove.forEach(e -> listAbove.add((int) e.getTranslateX()));

        LevelController.hero = new Hero(imageViewHero);
        LevelController.heroViewFromAbove = new HeroViewFromAbove(imageViewHeroViewFromAbove);
        LevelController.coin = new Coin(imageViewCoin);
        LevelController.coinViewFromAbove = new CoinViewFromAbove(imageViewCoinViewFromAbove);
        LevelController.gameRoot = gameRoot;
        LevelController.appRoot = appRoot;
        LevelController.extraGameRoot = extraGameRoot;
        LevelController.currentLevel = level;
        LevelController.backgroundGroundImage = backgroundGroundImage;
        LevelController.backgroundSkyImage = backgroundSkyImage;
        LevelController.list = list;
        LevelController.listOfObstacles = listOfObstacles;
        LevelController.listOfObstaclesViewFromAbove = listOfObstaclesViewFromAbove;
        LevelController.hero.setTranslateX(10);
        LevelController.hero.setTranslateY(550);
        LevelController.heroViewFromAbove.setTranslateX(10);
        LevelController.heroViewFromAbove.setTranslateY(700);
        LevelController.start(stage);
        stage.setFullScreen(true);
    }
}
