package com.example.demo.Controllers.Levels;

import com.example.demo.Controllers.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.util.ArrayList;
import java.util.List;

public class Level4 {
    public static Pane gameRoot = new Pane();
    public static Pane appRoot = new Pane();
    public static Pane extraGameRoot = new Pane();
    public static ImageView imageViewHero = new ImageView(new Image("Images/Sprites/SpriteHero.png"));
    public static ImageView imageViewHeroViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteHeroViewFromAbove.png"));
    public static ImageView imageViewCoin = new ImageView(new Image("Images/Sprites/SpriteCoin.png"));
    public static ImageView imageViewCoinViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteCoinViewFromAbove.png"));
    public static List<Obstacle> listOfObstacles = new ArrayList<>();
    public static List<ObstacleViewFromAbove> listOfObstaclesViewFromAbove = new ArrayList<>();
    public static List<Integer> list = new ArrayList<>();
    public static List<Integer> listAbove = new ArrayList<>();
    public static Integer level = 4;
    public static ImageView backgroundSkyImage = new ImageView(new Image("Images/Level4/Night.jpg"));
    public static ImageView backgroundGroundImage = new ImageView(new Image("Images/Level4/GroundAboveForNight.png"));
    public static void start(Stage stage) {
        Image wall = new Image("Images/Walls/Wall.jpg");
        Image wallX11H = new Image("Images/Walls/WallX11H.jpg");
        Image wallX3V = new Image("Images/Walls/WallX3V.jpg");
        Image wallX5V = new Image("Images/Walls/WallX5V.jpg");
        Obstacle obstacle = new Obstacle(3000, 250, new Image("Images/Level4/GroundForNight.png"));
        Obstacle obstacle3 = new Obstacle(70, 70, wall);
        Obstacle obstacle4 = new Obstacle(70, 70, wall);
        Obstacle obstacle5 = new Obstacle(70, 70, wall);
        Obstacle obstacle6 = new Obstacle(710, 70, wallX11H);
        Obstacle obstacle7 = new Obstacle(710, 70, wallX11H);
        Obstacle obstacle8 = new Obstacle(70, 70, wall);
        Obstacle obstacle9 = new Obstacle(70, 70, wall);
        Obstacle obstacle10 = new Obstacle(70, 70, wall);
        Obstacle obstacle13 = new Obstacle(70, 70, wall);
        Obstacle obstacle14 = new Obstacle(70, 210, wallX3V);
        Obstacle obstacle11 = new Obstacle(70, 70, wall);
        Obstacle obstacle12 = new Obstacle(710, 70, wallX11H);
        Obstacle obstacle15 = new Obstacle(70, 350, wallX5V);
        Obstacle obstacle16 = new Obstacle(70, 70, wall);
        Obstacle obstacle17 = new Obstacle(70, 70, wall);
        Image longWall = new Image("Images/Walls/LongWall.jpg");
        Image wallX8H = new Image("Images/Walls/WallX8H.jpg");
        Image wallX8V = new Image("Images/Walls/WallX8V.jpg");
        Image wallX5H = new Image("Images/Walls/WallX5H.jpg");
        Image wallX3H = new Image("Images/Walls/WallX3H.jpg");
        ObstacleViewFromAbove obstacleViewFromAbove8 = new ObstacleViewFromAbove(70, 900, longWall);
        ObstacleViewFromAbove obstacleViewFromAbove9 = new ObstacleViewFromAbove(70, 900, longWall);
        ObstacleViewFromAbove obstacleViewFromAbove10 = new ObstacleViewFromAbove(70, 900, longWall);
        ObstacleViewFromAbove obstacleViewFromAbove11 = new ObstacleViewFromAbove(560, 70, wallX8H);
        ObstacleViewFromAbove obstacleViewFromAbove12 = new ObstacleViewFromAbove(70, 545, wallX8V);
        ObstacleViewFromAbove obstacleViewFromAbove13 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove14 = new ObstacleViewFromAbove(350, 70, wallX5H);
        ObstacleViewFromAbove obstacleViewFromAbove15 = new ObstacleViewFromAbove(560, 70, wallX8H);
        ObstacleViewFromAbove obstacleViewFromAbove16 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove17 = new ObstacleViewFromAbove(70, 550, wallX8V);
        ObstacleViewFromAbove obstacleViewFromAbove18 = new ObstacleViewFromAbove(200, 70, wallX3H);
        ObstacleViewFromAbove obstacleViewFromAbove19 = new ObstacleViewFromAbove(70, 210, wallX3V);
        ObstacleViewFromAbove obstacleViewFromAbove20 = new ObstacleViewFromAbove(70, 210, wallX3V);
        ObstacleViewFromAbove obstacleViewFromAbove21 = new ObstacleViewFromAbove(80, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove22 = new ObstacleViewFromAbove(80, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove23 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove24 = new ObstacleViewFromAbove(70, 900, longWall);
        ObstacleViewFromAbove obstacleViewFromAbove25 = new ObstacleViewFromAbove(770, 70, wallX11H);
        ObstacleViewFromAbove obstacleViewFromAbove26 = new ObstacleViewFromAbove(70, 900, longWall);
        ObstacleViewFromAbove obstacleViewFromAbove27 = new ObstacleViewFromAbove(70, 900, longWall);
        ObstacleViewFromAbove obstacleViewFromAbove28 = new ObstacleViewFromAbove(70, 900, longWall);
        ObstacleViewFromAbove obstacleViewFromAbove29 = new ObstacleViewFromAbove(70, 210, wallX3V);
        ObstacleViewFromAbove obstacleViewFromAbove30 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove31 = new ObstacleViewFromAbove(70, 900, longWall);
        obstacle.setTranslateY(630);
        obstacle3.setTranslateX(70);
        obstacle3.setTranslateY(560);
        obstacle4.setTranslateX(70);
        obstacle4.setTranslateY(490);
        obstacle5.setTranslateX(1950);
        obstacle5.setTranslateY(345);
        obstacle6.setTranslateY(560);
        obstacle6.setTranslateX(220);
        obstacle7.setTranslateY(490);
        obstacle7.setTranslateX(220);
        obstacle8.setTranslateX(1000);
        obstacle8.setTranslateY(560);
        obstacle9.setTranslateX(220);
        obstacle9.setTranslateY(420);
        obstacle10.setTranslateX(400);
        obstacle10.setTranslateY(345);
        obstacle11.setTranslateX(610);
        obstacle13.setTranslateY(345);
        obstacle13.setTranslateX(820);
        obstacle11.setTranslateY(345);
        obstacle12.setTranslateX(1000);
        obstacle12.setTranslateY(345);
        obstacle14.setTranslateX(2260);
        obstacle14.setTranslateY(420);
        obstacle15.setTranslateX(2600);
        obstacle15.setTranslateY(280);
        obstacle16.setTranslateX(2920);
        obstacle16.setTranslateY(200);
        obstacle17.setTranslateX(2850);
        obstacle17.setTranslateY(200);
        obstacleViewFromAbove8.setTranslateX(220);
        obstacleViewFromAbove8.setTranslateY(-105);
        obstacleViewFromAbove9.setTranslateX(70);
        obstacleViewFromAbove9.setTranslateY(80);
        obstacleViewFromAbove10.setTranslateX(860);
        obstacleViewFromAbove10.setTranslateY(100);
        obstacleViewFromAbove11.setTranslateX(220);
        obstacleViewFromAbove11.setTranslateY(725);
        obstacleViewFromAbove12.setTranslateX(710);
        obstacleViewFromAbove12.setTranslateY(250);
        obstacleViewFromAbove13.setTranslateX(710);
        obstacleViewFromAbove13.setTranslateY(660);
        obstacleViewFromAbove14.setTranslateX(360);
        obstacleViewFromAbove14.setTranslateY(100);
        obstacleViewFromAbove15.setTranslateX(290);
        obstacleViewFromAbove15.setTranslateY(-60);
        obstacleViewFromAbove16.setTranslateX(850);
        obstacleViewFromAbove16.setTranslateY(-60);
        obstacleViewFromAbove17.setTranslateX(360);
        obstacleViewFromAbove17.setTranslateY(100);
        obstacleViewFromAbove18.setTranslateX(420);
        obstacleViewFromAbove18.setTranslateY(580);
        obstacleViewFromAbove19.setTranslateX(560);
        obstacleViewFromAbove19.setTranslateY(250);
        obstacleViewFromAbove20.setTranslateX(510);
        obstacleViewFromAbove20.setTranslateY(250);
        obstacleViewFromAbove21.setTranslateX(780);
        obstacleViewFromAbove21.setTranslateY(100);
        obstacleViewFromAbove22.setTranslateX(630);
        obstacleViewFromAbove22.setTranslateY(390);
        obstacleViewFromAbove23.setTranslateX(710);
        obstacleViewFromAbove23.setTranslateY(100);
        obstacleViewFromAbove24.setTranslateX(1000);
        obstacleViewFromAbove25.setTranslateX(1000);
        obstacleViewFromAbove25.setTranslateY(600);
        obstacleViewFromAbove26.setTranslateX(1950);
        obstacleViewFromAbove27.setTranslateX(2260);
        obstacleViewFromAbove28.setTranslateX(2600);
        obstacleViewFromAbove28.setTranslateY(-400);
        obstacleViewFromAbove31.setTranslateX(2600);
        obstacleViewFromAbove31.setTranslateY(800);
        obstacleViewFromAbove29.setTranslateX(2850);
        obstacleViewFromAbove29.setTranslateY(670);
        obstacleViewFromAbove30.setTranslateX(2920);
        obstacleViewFromAbove30.setTranslateY(670);
        listOfObstacles.add(obstacle);
        listOfObstacles.add(obstacle3);
        listOfObstacles.add(obstacle4);
        listOfObstacles.add(obstacle5);
        listOfObstacles.add(obstacle6);
        listOfObstacles.add(obstacle7);
        listOfObstacles.add(obstacle8);
        listOfObstacles.add(obstacle9);
        listOfObstacles.add(obstacle10);
        listOfObstacles.add(obstacle11);
        listOfObstacles.add(obstacle12);
        listOfObstacles.add(obstacle13);
        listOfObstacles.add(obstacle14);
        listOfObstacles.add(obstacle15);
        listOfObstacles.add(obstacle16);
        listOfObstacles.add(obstacle17);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove8);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove9);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove10);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove11);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove12);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove13);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove14);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove15);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove16);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove17);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove19);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove20);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove18);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove21);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove22);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove23);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove24);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove25);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove26);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove27);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove28);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove29);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove30);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove31);
        listOfObstacles.forEach(e -> list.add((int) e.getTranslateX()));
        listOfObstaclesViewFromAbove.forEach(e -> listAbove.add((int) e.getTranslateX()));

        LevelController.hero = new Hero(imageViewHero);
        LevelController.heroViewFromAbove = new HeroViewFromAbove(imageViewHeroViewFromAbove);
        LevelController.coin = new Coin(imageViewCoin);
        LevelController.coinViewFromAbove = new CoinViewFromAbove(imageViewCoinViewFromAbove);
        LevelController.gameRoot = gameRoot;
        LevelController.appRoot = appRoot;
        LevelController.extraGameRoot = extraGameRoot;
        LevelController.currentLevel = level;
        LevelController.backgroundGroundImage = backgroundGroundImage;
        LevelController.backgroundSkyImage = backgroundSkyImage;
        LevelController.list = list;
        LevelController.listOfObstacles = listOfObstacles;
        LevelController.listOfObstaclesViewFromAbove = listOfObstaclesViewFromAbove;
        LevelController.hero.setTranslateX(10);
        LevelController.hero.setTranslateY(550);
        LevelController.heroViewFromAbove.setTranslateX(10);
        LevelController.heroViewFromAbove.setTranslateY(700);
        LevelController.start(stage);
        stage.setFullScreen(true);
    }
}
