package com.example.demo.Controllers.Levels;
import com.example.demo.Controllers.*;

import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.util.ArrayList;
import java.util.List;

public class Level0 {
    public static Pane gameRoot = new Pane();
    public static Pane appRoot = new Pane();
    public static Pane extraGameRoot = new Pane();
    public static ImageView imageViewHero = new ImageView(new Image("Images/Sprites/SpriteHero.png"));
    public static ImageView imageViewHeroViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteHeroViewFromAbove.png"));
    public static ImageView imageViewCoin = new ImageView(new Image("Images/Sprites/SpriteCoin.png"));
    public static ImageView imageViewCoinViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteCoinViewFromAbove.png"));
    public static List<Obstacle> listOfObstacles = new ArrayList<>();
    public static List<ObstacleViewFromAbove> listOfObstaclesViewFromAbove = new ArrayList<>();
    public static List<Integer> list = new ArrayList<>();
    public static List<Integer> listAbove = new ArrayList<>();
    public static Integer level = 0;
    public static ImageView backgroundSkyImage = new ImageView(new Image("Images/Level0/Sky.jpg"));
    public static ImageView backgroundGroundImage = new ImageView(new Image("Images/Level0/GroundAbove.png"));
    public static void start(Stage stage) {
        LevelController.hero = new Hero(imageViewHero);
        LevelController.heroViewFromAbove = new HeroViewFromAbove(imageViewHeroViewFromAbove);
        LevelController.coin = new Coin(imageViewCoin);
        LevelController.coinViewFromAbove = new CoinViewFromAbove(imageViewCoinViewFromAbove);
        LevelController.gameRoot = gameRoot;
        LevelController.appRoot = appRoot;
        LevelController.extraGameRoot = extraGameRoot;
        LevelController.currentLevel = level;
        LevelController.backgroundSkyImage = backgroundSkyImage;
        LevelController.backgroundGroundImage = backgroundGroundImage;

        Image wall = new Image("Images/Walls/Wall.jpg");
        Image wallWithGrass = new Image("Images/Walls/WallWithGrass.jpg");
        Obstacle obstacle = new Obstacle(3000, 250, new Image("Images/Level0/Ground.jpg"));
        Obstacle obstacle2 = new Obstacle(70, 70, wallWithGrass);
        Obstacle obstacle3 = new Obstacle(70, 70, wall);
        Obstacle obstacle4 = new Obstacle(70, 70, wall);
        Obstacle obstacle5 = new Obstacle(70, 70, wallWithGrass);
        Obstacle obstacle6 = new Obstacle(70, 70, wallWithGrass);
        Image longWall = new Image("Images/Walls/LongWall.jpg");
        ObstacleViewFromAbove obstacleViewFromAbove = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove2 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove3 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove4 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove5 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove6 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove7 = new ObstacleViewFromAbove(70, 70, wall);
        ObstacleViewFromAbove obstacleViewFromAbove8 = new ObstacleViewFromAbove(70, 900,longWall);
        obstacle.setTranslateY(630);
        obstacle2.setTranslateY(560);
        obstacle3.setTranslateX(1600);
        obstacle3.setTranslateY(560);
        obstacle4.setTranslateX(1600);
        obstacle4.setTranslateY(490);
        obstacle5.setTranslateX(1600);
        obstacle5.setTranslateY(421);
        obstacle6.setTranslateY(560);
        obstacle6.setTranslateX(2000);
        obstacleViewFromAbove.setTranslateY(795);
        obstacleViewFromAbove2.setTranslateX(1600);
        obstacleViewFromAbove2.setTranslateY(795);
        obstacleViewFromAbove3.setTranslateX(1600);
        obstacleViewFromAbove3.setTranslateY(725);
        obstacleViewFromAbove4.setTranslateX(1600);
        obstacleViewFromAbove4.setTranslateY(655);
        obstacleViewFromAbove5.setTranslateX(1600);
        obstacleViewFromAbove5.setTranslateY(585);
        obstacleViewFromAbove6.setTranslateX(1600);
        obstacleViewFromAbove7.setTranslateX(1600);
        obstacleViewFromAbove7.setTranslateY(70);
        obstacleViewFromAbove8.setTranslateX(2000);
        listOfObstacles.add(obstacle);
        listOfObstacles.add(obstacle2);
        listOfObstacles.add(obstacle3);
        listOfObstacles.add(obstacle4);
        listOfObstacles.add(obstacle5);
        listOfObstacles.add(obstacle6);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove2);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove3);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove4);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove5);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove6);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove7);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove8);
        listOfObstacles.forEach(e -> list.add((int) e.getTranslateX()));
        listOfObstaclesViewFromAbove.forEach(e -> listAbove.add((int) e.getTranslateX()));
        LevelController.list = list;
        LevelController.listOfObstacles = listOfObstacles;
        LevelController.listOfObstaclesViewFromAbove = listOfObstaclesViewFromAbove;
        LevelController.start(stage);
        stage.setFullScreen(true);
    }
}
