package com.example.demo.Controllers.Levels;

import com.example.demo.Controllers.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.util.ArrayList;
import java.util.List;

public class Level2 {
    public Pane gameRoot = new Pane();
    public Pane appRoot = new Pane();
    public Pane extraGameRoot = new Pane();
    public ImageView imageViewHero = new ImageView(new Image("Images/Sprites/SpriteHero.png"));
    public ImageView imageViewHeroViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteHeroViewFromAbove.png"));
    public ImageView imageViewCoin = new ImageView(new Image("Images/Sprites/SpriteCoin.png"));
    public ImageView imageViewCoinViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteCoinViewFromAbove.png"));
    public List<Obstacle> listOfObstacles = new ArrayList<>();
    public List<ObstacleAbove> listOfObstaclesViewFromAbove = new ArrayList<>();
    public List<Integer> list = new ArrayList<>();
    public List<Integer> listAbove = new ArrayList<>();
    public Integer level = 2;
    public ImageView backgroundSkyImage = new ImageView(new Image("Images/Level2/Forest.png"));
    public ImageView backgroundGroundImage = new ImageView(new Image("Images/Level2/GroundAboveForForest.png"));
    public Level2() {

    }
    public void start(Stage stage) {
        LevelController levelController = new LevelController();
        Image wall = new Image("Images/Walls/Wall.jpg");
        Image longWall = new Image("Images/Walls/LongWall.jpg");
        Image wallX5H = new Image("Images/Walls/WallX5H.jpg");
        Image wallX3H = new Image("Images/Walls/WallX3H.jpg");
        Image wallX3V = new Image("Images/Walls/WallX3V.jpg");
        Image wallX5V = new Image("Images/Walls/WallX5V.jpg");
        Image wallX7V = new Image("Images/Walls/WallX7V.jpg");
        Image wallX8H = new Image("Images/Walls/WallX8H.jpg");
        Image wallX11H = new Image("Images/Walls/WallX11H.jpg");
        Image wallX11V = new Image("Images/Walls/WallX11V.jpg");
        Obstacle obstacle = new Obstacle(3000, 250, new Image("Images/Level2/GroundForForest.png"));
        Obstacle obstacle2 = new Obstacle(70, 70, wall);
        Obstacle obstacle3 = new Obstacle(70, 70, wall);
        Obstacle obstacle5 = new Obstacle(770, 70, wallX11H);
        Obstacle obstacle6 = new Obstacle(560, 70, wallX8H);
        Obstacle obstacle9 = new Obstacle(770, 70, wallX11H);
        Obstacle obstacle10 = new Obstacle(560, 70, wallX8H);
        Obstacle obstacle7 = new Obstacle(70, 70, wall);
        Obstacle obstacle8 = new Obstacle(70, 70, wall);
        Obstacle obstacle11 = new Obstacle(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove = new ObstacleAbove(70, 770, wallX11V);
        ObstacleAbove obstacleViewFromAbove2 = new ObstacleAbove(70, 350, wallX5V);
        ObstacleAbove obstacleViewFromAbove3 = new ObstacleAbove(70, 350, wallX5V);
        ObstacleAbove obstacleViewFromAbove4 = new ObstacleAbove(350, 70, wallX5H);
        ObstacleAbove obstacleViewFromAbove5 = new ObstacleAbove(350, 70, wallX5H);
        ObstacleAbove obstacleViewFromAbove6 = new ObstacleAbove(70, 350, wallX5V);
        ObstacleAbove obstacleViewFromAbove7 = new ObstacleAbove(70, 490, wallX7V);
        ObstacleAbove obstacleViewFromAbove9 = new ObstacleAbove(560, 70, wallX8H);
        ObstacleAbove obstacleViewFromAbove11 = new ObstacleAbove(560, 70, wallX8H);
        ObstacleAbove obstacleViewFromAbove10 = new ObstacleAbove(70, 490, wallX7V);
        ObstacleAbove obstacleViewFromAbove12 = new ObstacleAbove(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove13 = new ObstacleAbove(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove14 = new ObstacleAbove(70, 900, longWall);
        ObstacleAbove obstacleViewFromAbove15 = new ObstacleAbove(70, 210, wallX3V);
        ObstacleAbove obstacleViewFromAbove16 = new ObstacleAbove(70, 210, wallX3V);
        ObstacleAbove obstacleViewFromAbove17 = new ObstacleAbove(70, 210, wallX3V);
        ObstacleAbove obstacleViewFromAbove18 = new ObstacleAbove(210, 70, wallX3H);
        ObstacleAbove obstacleViewFromAbove19 = new ObstacleAbove(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove20 = new ObstacleAbove(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove21 = new ObstacleAbove(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove22 = new ObstacleAbove(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove23 = new ObstacleAbove(560, 70, wallX8H);
        ObstacleAbove obstacleViewFromAbove24 = new ObstacleAbove(70, 70, wall);
        ObstacleAbove obstacleViewFromAbove25 = new ObstacleAbove(210, 70, wallX3H);
        obstacle.setTranslateY(630);
        obstacle2.setTranslateX(2920);
        obstacle2.setTranslateY(420);
        obstacle3.setTranslateX(2850);
        obstacle3.setTranslateY(560);
        obstacle5.setTranslateX(700);
        obstacle5.setTranslateY(560);
        obstacle6.setTranslateY(560);
        obstacle6.setTranslateX(1440);
        obstacle9.setTranslateX(700);
        obstacle9.setTranslateY(490);
        obstacle10.setTranslateY(490);
        obstacle10.setTranslateX(1440);
        obstacle7.setTranslateX(2850);
        obstacle7.setTranslateY(490);
        obstacle8.setTranslateX(2850);
        obstacle8.setTranslateY(420);
        obstacle11.setTranslateX(2500);
        obstacle11.setTranslateY(560);
        obstacleViewFromAbove.setTranslateX(1890);
        obstacleViewFromAbove2.setTranslateX(700);
        obstacleViewFromAbove2.setTranslateY(490);
        obstacleViewFromAbove3.setTranslateX(700);
        obstacleViewFromAbove4.setTranslateX(910);
        obstacleViewFromAbove5.setTranslateX(910);
        obstacleViewFromAbove5.setTranslateY(70);
        obstacleViewFromAbove6.setTranslateX(1190);
        obstacleViewFromAbove7.setTranslateX(980);
        obstacleViewFromAbove7.setTranslateY(280);
        obstacleViewFromAbove9.setTranslateX(1400);
        obstacleViewFromAbove9.setTranslateY(350);
        obstacleViewFromAbove10.setTranslateX(1400);
        obstacleViewFromAbove10.setTranslateY(140);
        obstacleViewFromAbove11.setTranslateX(1190);
        obstacleViewFromAbove11.setTranslateY(770);
        obstacleViewFromAbove12.setTranslateX(2920);
        obstacleViewFromAbove12.setTranslateY(500);
        obstacleViewFromAbove13.setTranslateX(2850);
        obstacleViewFromAbove13.setTranslateY(500);
        obstacleViewFromAbove14.setTranslateX(2500);
        obstacleViewFromAbove15.setTranslateX(1610);
        obstacleViewFromAbove16.setTranslateX(1680);
        obstacleViewFromAbove16.setTranslateY(560);
        obstacleViewFromAbove17.setTranslateX(1820);
        obstacleViewFromAbove17.setTranslateY(140);
        obstacleViewFromAbove18.setTranslateX(1050);
        obstacleViewFromAbove18.setTranslateY(490);
        obstacleViewFromAbove19.setTranslateX(770);
        obstacleViewFromAbove19.setTranslateY(490);
        obstacleViewFromAbove20.setTranslateX(770);
        obstacleViewFromAbove20.setTranslateY(560);
        obstacleViewFromAbove21.setTranslateX(1190);
        obstacleViewFromAbove21.setTranslateY(700);
        obstacleViewFromAbove22.setTranslateX(1610);
        obstacleViewFromAbove22.setTranslateY(560);
        obstacleViewFromAbove23.setTranslateX(1190);
        obstacleViewFromAbove23.setTranslateY(840);
        obstacleViewFromAbove24.setTranslateX(700);
        obstacleViewFromAbove24.setTranslateY(840);
        obstacleViewFromAbove25.setTranslateX(700);
        listOfObstacles.add(obstacle);
        listOfObstacles.add(obstacle2);
        listOfObstacles.add(obstacle3);
        listOfObstacles.add(obstacle5);
        listOfObstacles.add(obstacle6);
        listOfObstacles.add(obstacle7);
        listOfObstacles.add(obstacle8);
        listOfObstacles.add(obstacle9);
        listOfObstacles.add(obstacle10);
        listOfObstacles.add(obstacle11);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove2);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove3);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove4);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove5);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove6);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove7);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove9);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove10);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove11);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove12);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove13);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove14);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove15);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove16);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove17);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove18);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove19);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove20);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove21);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove22);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove23);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove24);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove25);
        listOfObstacles.forEach(e -> list.add((int) e.getTranslateX()));
        listOfObstaclesViewFromAbove.forEach(e -> listAbove.add((int) e.getTranslateX()));

        levelController.hero = new Hero(levelController, imageViewHero);
        levelController.heroAbove = new HeroAbove(levelController, imageViewHeroViewFromAbove);
        levelController.coin = new Coin(levelController, imageViewCoin);
        levelController.coinAbove = new CoinAbove(levelController, imageViewCoinViewFromAbove);
        levelController.gameRoot = gameRoot;
        levelController.appRoot = appRoot;
        levelController.extraGameRoot = extraGameRoot;
        levelController.currentLevel = level;
        levelController.backgroundGroundImage = backgroundGroundImage;
        levelController.backgroundSkyImage = backgroundSkyImage;
        levelController.list = list;
        levelController.listOfObstacles = listOfObstacles;
        levelController.listOfObstaclesAbove = listOfObstaclesViewFromAbove;
        levelController.hero.setTranslateX(10);
        levelController.hero.setTranslateY(480);
        levelController.heroAbove.setTranslateX(10);
        levelController.heroAbove.setTranslateY(700);
        levelController.start(stage);
        stage.setFullScreen(true);
    }
}
