package com.example.demo.Controllers.Levels;

import com.example.demo.Controllers.*;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.util.ArrayList;
import java.util.List;

public class Level3 {
    public Pane gameRoot = new Pane();
    public Pane appRoot = new Pane();
    public Pane extraGameRoot = new Pane();
    public ImageView imageViewHero = new ImageView(new Image("Images/Sprites/SpriteHero.png"));
    public ImageView imageViewHeroViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteHeroViewFromAbove.png"));
    public ImageView imageViewCoin = new ImageView(new Image("Images/Sprites/SpriteCoin.png"));
    public ImageView imageViewCoinViewFromAbove = new ImageView(new Image("Images/Sprites/SpriteCoinViewFromAbove.png"));
    public List<Obstacle> listOfObstacles = new ArrayList<>();
    public List<ObstacleAbove> listOfObstaclesViewFromAbove = new ArrayList<>();
    public List<Integer> list = new ArrayList<>();
    public List<Integer> listAbove = new ArrayList<>();
    public Integer level = 3;
    public ImageView backgroundSkyImage = new ImageView(new Image("Images/Level3/Moonshine.png"));
    public ImageView backgroundGroundImage = new ImageView(new Image("Images/Level3/GroundAboveForMoonshine.png"));
    public Level3() {}
    public void start(Stage stage) {
        LevelController levelController = new LevelController();
        Image wall = new Image("Images/Walls/Wall.jpg");
        Image wallX3V = new Image("Images/Walls/WallX3V.jpg");
        Image wallX11H = new Image("Images/Walls/WallX11H.jpg");
        Image wallWithGrass = new Image("Images/Walls/Wall.jpg");
        Obstacle obstacle = new Obstacle(3000, 250, new Image("Images/Level3/GroundForMoonshine.png"));
        Obstacle obstacle2 = new Obstacle(70, 70, wall);
        Obstacle obstacle3 = new Obstacle(70, 70, wall);
        Obstacle obstacle4 = new Obstacle(70, 210, wallX3V);
        Obstacle obstacle5 = new Obstacle(70, 70, wallWithGrass);
        Obstacle obstacle6 = new Obstacle(70, 70, wallWithGrass);
        Obstacle obstacle7 = new Obstacle(70, 70, wall);
        Obstacle obstacle8 = new Obstacle(70, 70, wall);
        Obstacle obstacle9 = new Obstacle(70, 70, wall);
        Obstacle obstacle10 = new Obstacle(70, 70, wall);
        Obstacle obstacle11 = new Obstacle(70, 210, wallX3V);
        Obstacle obstacle12 = new Obstacle(70, 70, wall);
        Obstacle obstacle13 = new Obstacle(70, 70, wall);
        Obstacle obstacle14 = new Obstacle(770, 70, wallX11H);
        Obstacle obstacle15 = new Obstacle(70, 210, wallX3V);
        Obstacle obstacle16 = new Obstacle(70, 70, wall);
        Obstacle obstacle17 = new Obstacle(70, 70, wall);
        Obstacle obstacle18 = new Obstacle(70, 70, wall);
        Obstacle obstacle19 = new Obstacle(70, 70, wall);
        Obstacle obstacle20 = new Obstacle(70, 70, wall);
        Image longWall = new Image("Images/Walls/LongWall.jpg");
        Image wall11x13 = new Image("Images/Walls/WallX11x13.jpg");
        ObstacleAbove obstacleViewFromAbove2 = new ObstacleAbove(70, 70,wall);
        ObstacleAbove obstacleViewFromAbove3 = new ObstacleAbove(70, 70,wall);
        ObstacleAbove obstacleViewFromAbove4 = new ObstacleAbove(70, 70,wall);
        ObstacleAbove obstacleViewFromAbove5 = new ObstacleAbove(70, 70,wall);
        ObstacleAbove obstacleViewFromAbove6 = new ObstacleAbove(70, 70,wall);
        ObstacleAbove obstacleViewFromAbove7 = new ObstacleAbove(70, 70,wall);
        ObstacleAbove obstacleViewFromAbove8 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove9 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove10 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove11 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove12 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove13 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove14 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove15 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove16 = new ObstacleAbove(70, 900,longWall);
        ObstacleAbove obstacleViewFromAbove17 = new ObstacleAbove(770, 900,wall11x13);
        obstacle.setTranslateY(630);
        obstacle2.setTranslateX(770);
        obstacle2.setTranslateY(490);
        obstacle3.setTranslateX(770);
        obstacle3.setTranslateY(560);
        obstacle4.setTranslateX(840);
        obstacle4.setTranslateY(420);
        obstacle5.setTranslateX(1350);
        obstacle5.setTranslateY(421);
        obstacle6.setTranslateX(2330);
        obstacle6.setTranslateY(560);
        obstacle7.setTranslateX(700);
        obstacle7.setTranslateY(560);
        obstacle8.setTranslateX(560);
        obstacle8.setTranslateY(420);
        obstacle9.setTranslateX(490);
        obstacle9.setTranslateY(420);
        obstacle10.setTranslateX(490);
        obstacle10.setTranslateY(350);
        obstacle11.setTranslateX(910);
        obstacle11.setTranslateY(280);
        obstacle12.setTranslateX(420);
        obstacle12.setTranslateY(280);
        obstacle13.setTranslateX(560);
        obstacle13.setTranslateY(180);
        obstacle14.setTranslateX(1490);
        obstacle14.setTranslateY(485);
        obstacle15.setTranslateX(2400);
        obstacle15.setTranslateY(420);
        obstacle16.setTranslateX(1550);
        obstacle16.setTranslateY(340);
        obstacle17.setTranslateX(1760);
        obstacle17.setTranslateY(340);
        obstacle18.setTranslateX(1970);
        obstacle18.setTranslateY(340);
        obstacle19.setTranslateX(2180);
        obstacle19.setTranslateY(340);
        obstacle20.setTranslateX(2400);
        obstacle20.setTranslateY(350);
        obstacleViewFromAbove2.setTranslateX(1600);
        obstacleViewFromAbove2.setTranslateY(795);
        obstacleViewFromAbove3.setTranslateX(1600);
        obstacleViewFromAbove3.setTranslateY(725);
        obstacleViewFromAbove4.setTranslateX(1600);
        obstacleViewFromAbove4.setTranslateY(655);
        obstacleViewFromAbove5.setTranslateX(1600);
        obstacleViewFromAbove5.setTranslateY(585);
        obstacleViewFromAbove6.setTranslateX(1600);
        obstacleViewFromAbove6.setTranslateY(0);
        obstacleViewFromAbove7.setTranslateX(1600);
        obstacleViewFromAbove7.setTranslateY(70);
        obstacleViewFromAbove8.setTranslateX(420);
        obstacleViewFromAbove9.setTranslateX(490);
        obstacleViewFromAbove10.setTranslateX(560);
        obstacleViewFromAbove11.setTranslateX(700);
        obstacleViewFromAbove12.setTranslateX(770);
        obstacleViewFromAbove13.setTranslateX(840);
        obstacleViewFromAbove14.setTranslateX(1350);
        obstacleViewFromAbove17.setTranslateX(1490);
        obstacleViewFromAbove16.setTranslateX(2330);
        obstacleViewFromAbove15.setTranslateX(2400);
        listOfObstacles.add(obstacle);
        listOfObstacles.add(obstacle2);
        listOfObstacles.add(obstacle3);
        listOfObstacles.add(obstacle4);
        listOfObstacles.add(obstacle5);
        listOfObstacles.add(obstacle6);
        listOfObstacles.add(obstacle7);
        listOfObstacles.add(obstacle8);
        listOfObstacles.add(obstacle9);
        listOfObstacles.add(obstacle10);
        listOfObstacles.add(obstacle11);
        listOfObstacles.add(obstacle12);
        listOfObstacles.add(obstacle13);
        listOfObstacles.add(obstacle14);
        listOfObstacles.add(obstacle15);
        listOfObstacles.add(obstacle16);
        listOfObstacles.add(obstacle17);
        listOfObstacles.add(obstacle18);
        listOfObstacles.add(obstacle19);
        listOfObstacles.add(obstacle20);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove2);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove3);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove4);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove5);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove6);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove7);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove8);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove9);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove10);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove11);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove12);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove13);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove14);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove15);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove16);
        listOfObstaclesViewFromAbove.add(obstacleViewFromAbove17);
        listOfObstacles.forEach(e -> list.add((int) e.getTranslateX()));
        listOfObstaclesViewFromAbove.forEach(e -> listAbove.add((int) e.getTranslateX()));

        levelController.hero = new Hero(levelController, imageViewHero);
        levelController.heroAbove = new HeroAbove(levelController, imageViewHeroViewFromAbove);
        levelController.coin = new Coin(levelController, imageViewCoin);
        levelController.coinAbove = new CoinAbove(levelController, imageViewCoinViewFromAbove);
        levelController.gameRoot = gameRoot;
        levelController.appRoot = appRoot;
        levelController.extraGameRoot = extraGameRoot;
        levelController.currentLevel = level;
        levelController.backgroundGroundImage = backgroundGroundImage;
        levelController.backgroundSkyImage = backgroundSkyImage;
        levelController.list = list;
        levelController.listOfObstacles = listOfObstacles;
        levelController.listOfObstaclesAbove = listOfObstaclesViewFromAbove;
        levelController.hero.setTranslateX(10);
        levelController.hero.setTranslateY(480);
        levelController.heroAbove.setTranslateX(10);
        levelController.heroAbove.setTranslateY(700);
        levelController.start(stage);
        stage.setFullScreen(true);
    }
}